#%RAML 1.0 NamedExample
persons_example:
  value:
    -
      fullname: "Misael"
      lastname: "Pare"
      age: 22
      gender: "Hombre"
      country: "Arg"
    -
      fullname: "Sebastian"
      lastname: "Pare"
      age: 22
      gender: "Hombre"
      country: "Arg"